### ISSUE TITLE
Type compatibility errors with Flutter 3.35.3 - BottomAppBarTheme, InputDecorationTheme, AppBarTheme breaking changes

### ISSUE THREAD

**Issue by chems17** [peiffer-innovations/json_theme#287]
Describe the bug
The package fails to compile with Flutter 3.35.3 due to type compatibility errors. Flutter appears to have introduced breaking changes in Material Design theme types, causing multiple compilation errors in both theme_decoder.dart and theme_encoder.dart files.
To Reproduce

Create a Flutter project using Flutter 3.35.3
Add json_theme: 9.0.1+2 as a dependency (or any package that depends on it)
Run flutter pub get
Execute flutter build for any platform
Observe compilation errors

Expected behavior
The package should compile successfully with Flutter 3.35.3, maintaining compatibility with the current stable Flutter release.
Example PR
Cannot provide a working PR example since this is a compilation-time issue that prevents any code using this package from building. The specific errors encountered are:
theme_decoder.dart:11688:28: Error: The argument type 'BottomAppBarTheme?' can't be assigned to the parameter type 'BottomAppBarThemeData?'
theme_encoder.dart:1862:17: Error: The argument type 'InputDecorationThemeData?' can't be assigned to the parameter type 'InputDecorationTheme?'  
theme_encoder.dart:7192:48: Error: The argument type 'AppBarThemeData' can't be assigned to the parameter type 'AppBarTheme?'
theme_encoder.dart:5478:15: Error: The type 'ShowValueIndicator' is not exhaustively matched by the switch cases since it doesn't match 'ShowValueIndicator.onDrag'
Additional Context
This issue affects all downstream packages that depend on json_theme, including json_dynamic_widget. The problem appears to stem from Flutter renaming/restructuring theme data classes in recent versions. A fix would likely require updating type references throughout the codebase to match Flutter 3.35.x expectations.
